### ISSUE TITLE
'WebKit/WebKit.h' file not found

### ISSUE THREAD

**Issue by ali-sao** [pavjacko/react-native-vanilla#17]
When I run the app over tvOS I face this error : 'WebKit/WebKit.h' file not found .
MacOS Mojave 10.14 .
Xcode Version 10.1 (10B61)
React version 16.5.1
ReactNative version 0.57.1

Any suggestions ? thanks

**Comment by asantarissy** [comment]
Hey @ali-sao, I think this link might help you [RCTConvert.h diff](https://github.com/facebook/react-native/commit/d82b79870c7c5386b71bdaf6c5f3a7d4e6e85ecc)

**Comment by ali-sao** [comment]
hello @asantarissy , thanks for helping out , I already tried this approach , unfortunately other sources are dependent on the WebKit.h ,which leads to an infinite fixes and conditional imports that messes up tvOS project.

**Comment by pavjacko** [comment]
@ali-sao @asantarissy fixed in `0.8.1`

**Comment by ali-sao** [comment]
Thanks @pavjacko
