### ISSUE TITLE
webOS app fails to install on LG 4.0 emulator

### ISSUE THREAD

**Issue by rdobda-gaia** [pavjacko/react-native-vanilla#18]
This is a little weird. I was having this issue before, then it worked, and now i'm having it again. Essentially, the ipk fails to install on the latest emulator from LG (4.0). When i use the script i get "ares-install: Installation failure (the reason may be unsupported architecture)" And when i try to install it using the emulator's app manager, i get "Installation Failed." (i can install a different ipk created from the lg IDE with no issue). This is strange because i was seeing this error last week, then i cleared all the apps off of the emulator and was able to get it to install, then stepped away for a few days, and now this week it fails again. So, it seems intermittent, though there have been some code dependency updates since then, i doubt those would have introduced the issue. I am on macOS mojave. I am curious if you can reproduce the issue. Also, there's definitely a small bug either way in the package.js anyway because the ipk is named differently than what's in the install script. Thank you for your support on this, i am very impressed with this starter project

**Comment by rdobda-gaia** [comment]
update: The weird thing is that if i open the webOSIDE, then "IMPORT" the /platforms/webos/ folder as a webOS project, then "Export application" to generate an ipk, then this IPK can be installed ok using the "App installer" of the emulator... so something is weird.

**Comment by pavjacko** [comment]
@rdobda-gaia latest 0.8.3 now supports ares cli directly. if you follow these instructions: https://github.com/pavjacko/react-native-vanilla#lg-webos it should work for you

**Comment by rdobda-gaia** [comment]
Great! This works now. Any idea why the logo/image doesn't show up on webos or tizen?
