### ISSUE TITLE
Webpack config overriden by rnv run -p web

### ISSUE THREAD

**Issue by danielmarino24i** [pavjacko/react-native-vanilla#46]
**RNV**: 0.19.3

Everytime I run `rnv run -p web` the webpack config is overriden.

Example:

1. Open `platformBuilds/YOUR_PROJECTExample_web/webpack.config.js`
2. Make any change
3. Save
4. run `rnv run -p web`
5. `platformBuilds/YOUR_PROJECTExample_web/webpack.config.js` is overriden, and changes lost

**Comment by pavjacko** [comment]
@danielmarino24i that is expected behaviour. if you want to control your webpack you need to run `rnv platform eject` then you should be able to edit your `platformTemplates` where your original webpack config resides

**Comment by CHaNGeTe** [comment]
👍
