### ISSUE TITLE
Add dependencies 

### ISSUE THREAD

**Issue by MwareSolutons** [pavjacko/react-native-vanilla#47]
hi great project!!!

I am a bit confused about adding project dependencies...

I would like to add for example react-native-google-cast 
can I still use npm install and npm link ?

Or do i go about this another way ?

**Comment by ali-sao** [comment]
Eject the plarforms and add the dependecies the traditional way we used to do in any typical react native project .

-npm install your dependency .
-Add your podspec or pod path to your podfile inside ios or tvos .
-pod install and that's it for apple .

For android , follow the manual steps provided by your dependency .

**Comment by MwareSolutons** [comment]
Got it thanks...!
