### ISSUE TITLE
Gradle 4.10 & 3.3.0-alpha08

### ISSUE THREAD

**Issue by Kompwu** [pavjacko/react-native-vanilla#7]
I tried to do the update myself but I can't get them to work.
I could help, but I need help...
It would also be necessary to go from `jre` to `jdk` since it is deprecated for kotlin.
If needed, I can open a PR with my current work.

**Comment by pavjacko** [comment]
@Kompwu, if you can open PR that would help to understand specific issue you're having or comment here with more info.

- Your OS
- Steps to reproduce
